### ISSUE TITLE
Git guard is not working after the latest release of Github

### ISSUE THREAD

**Issue by neloydas** [w17chm4n/gitguard#1]
git guard extension is not working after the latest release from hithub which changes the merge button to a drop-down list with three options. The extension should make the whole list red to guard a branch.

**Comment by w17chm4n** [comment]
Hey,

Thanks for the info! I didn't know that GitHub changed anything since I'm not currently using it as much I used to. I'll try to fix it in my spare time but feel free to contribute to speed up the release process.

**Comment by neloydas** [comment]
I'm also trying to contribute to it in my spare time. Might need some time as I'm not so well versed with javascript. Will try anyway. Thanks Neloy

**Comment by w17chm4n** [comment]
@neloydas I've just published version _1.3.0_ which makes this extension compatible with the newest version of GitHub.

**Comment by neloydas** [comment]
Thank you very much! My whole team was depending on this extension. Well done mate!
